"""Fig 1 — composite: NPIX null result + NPIX positive result + spectra + p-value ECDFs.

Both the null (magnetic stimulus) and positive (visual gratings) panels come from
the SAME exemplar unit (cluster 540, experiment 20230413_secondsite, Pigeon W25R,
hippocampus) -- it's non-significant across all 7 of its own magnetic-stimulus
trials (and both white-noise recs), yet significant at 3 of its 8 visual-gratings
orientations (all 3Hz: 45 degrees p<0.0001 NFC=7.79; 315 degrees p<0.0001 NFC=4.52;
270 degrees p=0.019 NFC=2.84). Using one neuron/session/probe for both panels is
a stronger story than two different units from two different sessions: it
preempts the "maybe that channel just wasn't picking up signal" critique, since
the same channel clearly does pick up signal (for the visual grating) but just
doesn't respond to the magnet.

This unit fires only modestly (~1.7-3.1Hz) -- a deliberate change from an
earlier iteration of this worktree (cluster 566, same experiment, ~20-27Hz),
which turned out to be a mistake for this figure's purpose despite satisfying
an earlier "prefer higher firing" request. The phasor-arrow colors in panel
B encode phase *relative to each trace's own window*, so a genuinely
stimulus-locked spike train should show arrows clustering on one dominant hue,
not a rainbow -- that's the whole visual point of the colorwheel. Cluster 566
was significant (p=0.0035) purely because of its very high spike count (n=1794
at 45 degrees); its actual phase concentration (circular resultant length
R=0.075) was tiny, so its arrows in panel B looked like uniform noise even
across 6 stimulus cycles -- a real "just significant, not astronomical" effect
can still be too visually diffuse to see by eye. Cluster 540, despite far fewer
spikes, has R=0.457 at 45 degrees (the tightest concentration found among this
experiment's null-to-mag, significant-to-visual candidates) -- its
visual-trace arrows in panel B visibly cluster on warm hues
(red/orange/yellow) across 15 stimulus cycles, while the magnetic trace's
arrows (null) stay scattered across the whole wheel. Firing rate and phase concentration turned out to trade off against each
other among this experiment's candidate units; satisfying "see a pattern by
eye" took priority here since that was the more recent, more specific request.

Choice of experiment matters here as much as choice of unit: unlike
20230414_firstsite (a previous iteration of this same worktree, cluster 100),
whose visual-gratings *population* only had 4.9-12.1% of units significant at
any given orientation -- a fairly weak "positive control" for the population
histogram in panel F -- 20230413_secondsite's visual_movinggratings3Hz
population has up to 22.0% of units significant at a single orientation (45
or 90 degrees), while its own mag recs stay near the ~2-9% chance rate. That
makes the population-level story in panels C-F honestly stronger, not just
the single-exemplar story in panel B. (Population significance fractions
per rec were scanned across all NPIX experiments with visual-gratings data;
see git history / session notes for the full comparison table.)

The best null (Mag3_inclined) and best positive (visual_movinggratings3Hz,
orientation 45) conditions are both at 3Hz, so this comparison isolates
modality rather than confounding it with frequency.

Mag3_inclined, not the plain (non-inclined) Mag3 trial, is used for the null
panels (2026-09-02) -- both are 3Hz and both are non-significant for this
unit (Mag3 p=0.708, Mag3_inclined p=0.374), so either satisfies the
modality-isolation argument above equally well. But Mag3's own 204-unit
population turned out to sit unusually far out on the tail of the
population-level p-value ECDF-deviation distribution across all comparable
NPIX null recordings (mean deviation -0.050, 2nd-most-extreme of 67 -- see
pipeline/manuscript/fig1E_qfrac_diagnostic.py, which confirmed this wasn't
fixable by any Q_frac choice and reflects finite-N sampling noise specific
to that recording, not a bug). Mag3_inclined's population sits right in the
middle of that same distribution (mean deviation -0.009), so panel E's
null-PDF/ECDF fit reads as unremarkable instead of an outlier, with no
other change to the figure's narrative.

Phasor arrows in panel B are colored by phase (cyclic `hsv` colormap, 0 to
one stimulus period) -- see the colorwheel legend between its two traces,
whose mapping the phase axes of panels C/D repeat in their tick colors.

A previous version of this figure (pipeline/manuscript/fig1_auditory.py)
instead compared magnetic stimulation to the 0.8Hz auditory white-noise
condition, using a different exemplar unit (cluster 106/experiment 20230415)
-- kept alongside this one for reference/comparison, not regenerated by
default. See its docstring for that version's own rationale.

Requires pipeline outputs:
  data/20230413_secondsite.nwb

Requires pre-extracted raw-voltage snippets (see fig1_extract_raw_snippets.py,
which is the only piece of this figure that needs NAS access):
  data/fig1_raw/mag_trace.npy
  data/fig1_raw/vis_trace.npy
  data/fig1_raw/vis_waveforms.npy

Usage:
    python pipeline/manuscript/fig1.py
    python pipeline/manuscript/fig1.py --out-dir figs/paper
"""
#%%
import argparse
from pathlib import Path

# Detect if running in Jupyter notebook (must do this before matplotlib.use)
try:
    from IPython import get_ipython
    in_notebook = get_ipython() is not None
except ImportError:
    in_notebook = False

import matplotlib
if not in_notebook:
    matplotlib.use("Agg")
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import matplotlib.transforms
import numpy as np
import pandas as pd
from scipy import ndimage

import colorcet  # noqa: F401 -- import side effect registers "cet_*" colormaps with matplotlib
from ecdfbounds import bootstrap_ecdf_band
from magpyneto2 import statistics
from magpyneto2.statistics import normalized_Fourier_CDF
from pipeline import nwb_io
from pipeline.schema import load_experiment

import format_parameters as FP
#%%
# ── NAS paths (only used by fig1_extract_raw_snippets.py, not this script) ──
# (Unlike 20230414_firstsite's stale YAML `folder:` root in a previous
# iteration of this worktree, 20230413_secondsite's YAML root matches the
# actual NAS layout -- confirmed by listing the NAS directly.)
RAW_DATA_ROOT = r"\\datanas\family\data_raw\20230413\second_site"
AGGREGATED_PATH = r"\\datanas\family\data_aggregated\20230413_secondsite"

# ── Column geometry ───────────────────────────────────────────────────────────
# Width of the narrow spacer column between the B and C columns, relative to
# each data column's own width, and the gap on either side of it. It holds
# the waveform + phase-colorwheel legends; both tolerate a fairly tight fit,
# so this is kept small to buy width for the data panels (and, in the top
# row, for the cartoons, which are height-limited and so gain proportionally
# as the figure narrows around them). cartoon_gs and bc_gs share these so
# each cartoon stays centered over the column it describes.
SPACER_COL_WIDTH = 0.26
COL_WSPACE = 0.07

# ── Top-row cartoons ──────────────────────────────────────────────────────────
# Hand-drawn schematics of the two stimulus configurations, sitting side by
# side in the top row directly above their own data columns: the magnetic
# coil pair (left, above panel B's magnetic trace) and the grating screen
# (right, above its visual trace). They live in the figure output directory alongside the PDFs rather
# than under data/ -- they're figure assets, not pipeline data.
CARTOON_MAG_PATH = Path(FP.OUT_DIR) / "Pig mag - August 26, 2026 18.51.58.jpg"
CARTOON_VIS_PATH = Path(FP.OUT_DIR) / "Pig screen - August 29, 2026 18.51.58.jpg"

# ── Experiment / exemplar unit ────────────────────────────────────────────────
EXPERIMENT = "20230413_secondsite"
CLUSTER_ID = 540  # single unit, used for both the null and positive panels

MAG_CONTINGENCY = "2023-04-13_17-06-27_W25R_second_site_mag3_inclined"
MAG_FREQ = 3
# Non-significant (p=0.374, NFC=1.40) across this unit's mag3_inclined trial
# -- of this unit's 7 null magnetic trials (p 0.374-0.916, all
# non-significant), this is the 3Hz one now used (see module docstring's
# "Mag3_inclined, not the plain Mag3" note for why, 2026-09-02), chosen to
# match VIS_FREQ below so the null-vs-positive comparison isolates modality,
# not frequency.
# 15 cycles at 3Hz (period 1/3 s), not 1 -- with the phasor arrows now
# phase-colored, a single-cycle window is diagnostically uninformative: phase
# is computed as time-since-window-start mod period, which for a window no
# longer than one period trivially increases monotonically for ANY spike
# train (locked or not) since real time itself is monotonic. Only across
# multiple cycles can the reader actually compare whether phase/color repeats
# consistently cycle-to-cycle (locked) or drifts (not). This unit fires only
# ~1.7Hz here, so 15 cycles (5s) -- rather than a smaller cycle count -- is
# needed just to get a handful of spikes to look at; see the module docstring
# for why a sparser-but-tighter-locking unit was chosen over a denser one.
MAG_WINDOW = (77.484, 82.484)  # 5s = 15 cycles at 3Hz, ~8 spikes, evenly spread

# Visual gratings: recname is NOT orientation-split in the raw OpenEphys
# folder (all 8 orientations are one continuous recording, played back to
# back as 8 long single-orientation blocks) -- the "_45" suffix only exists
# in modulation_df/fourier_df's post-hoc orientation split.
VIS_CONTINGENCY = "2023-04-13_17-31-40_W25R_second_site_visual_movinggratings3Hz_45"
# The raw OpenEphys folder itself has no orientation suffix (only
# modulation_df/fourier_df's post-hoc orientation split does) -- used only by
# fig1_extract_raw_snippets.py to open the right raw folder.
VIS_RAW_RECNAME = "2023-04-13_17-31-40_W25R_second_site_visual_movinggratings3Hz"
VIS_FREQ = 3
# Best-NFC of this unit's 3 significant visual-gratings orientations (all
# 3Hz: 45 degrees p<0.0001 NFC=7.79, 315 degrees p<0.0001 NFC=4.52, 270
# degrees p=0.019 NFC=2.84) -- also the tightest phase concentration
# (circular resultant length R=0.457) found among this experiment's
# null-to-mag, visual-significant candidates, which is what actually makes
# the phasor-arrow colors on panel B's visual trace visibly cluster by eye (see module
# docstring). Also 3Hz, matching MAG_FREQ, so the null-vs-positive comparison
# isolates modality, not frequency.
VIS_WINDOW = (91.789, 96.789)  # 5s = 15 cycles at 3Hz (see MAG_WINDOW comment), ~16 spikes

# Sampling rates for the pre-extracted raw-voltage snippets (see
# fig1_extract_raw_snippets.py, which prints these when it runs).
MAG_TRACE_SR = 30000
VIS_TRACE_SR = 30000

# Spike-raster tick linewidth, shared by both raw_NPIX panels (default is 2,
# which reads as visually heavy/blocky once many ticks are packed into a
# wider window).
RASTER_LW = 0.5

# Padding on the phase rasters and their PSTH overlays, as fractions of the
# phase span / cycle count / rate range -- the same treatment (and the same
# values) as Fig4A's rasters, see fig4.py's RASTER_PAD_X/RASTER_PAD_Y/
# PSTH_PAD_Y. Without it the axes limits snap exactly to the data, so ticks
# at phase 0/2*pi and on the first/last cycle are drawn half-under the
# spines, and a PSTH trough that reaches 0 Hz sits right on the raster's
# bottom spine.
RASTER_PAD_X = 0.03
RASTER_PAD_Y = 0.03
PSTH_PAD_Y   = 0.06

# Shrinks the phasor markers (via raw_NPIX's stem_scale) down from their
# full default size -- each spike still shows its phase as both a color and
# a pointing direction (the chevron shape), just smaller, so panel B's
# two traces read as a
# field of small phase markers rather than a dense cluster of larger ones.
ARROW_STEM_SCALE = 0.6

# Cyclic colormap for phase-coloring the phasor arrows in both raw_NPIX
# panels -- paired with a colorwheel legend (statistics.plot_phase_colorwheel)
# drawn between panel B's two traces. colorcet's CET_C6s (importing colorcet
# auto-registers it with matplotlib as "cet_CET_C6s") avoids "twilight"'s
# near-white anchor at phase=0, which would make arrows nearly invisible
# against this figure's white background.
PHASE_CMAP = "cet_CET_C6s"

# Raises the waveform + colorwheel legend stack within its own column, as a
# fraction of one legend cell's height. Both are lifted rather than just the
# wheel, so the pair keeps its own spacing. The wheel's bottom "3pi/2" label
# would otherwise sit right on top of panel D's label, which is annotated
# relative to the visual phase raster directly below it; there's headroom
# above the waveform to absorb the shift, since the two raw-trace titles it
# sits between are horizontally clear of this narrow middle column.
LEGEND_LIFT = 0.25

# ── Average spike-waveform panel ──────────────────────────────────────────────
# 100 randomly-sampled raw waveforms (seeded for reproducibility) for this
# unit, drawn from the visual-gratings recording (larger spike count of the
# two: 204 vs 95 for the mag trial).
N_WAVEFORMS = 100
WAVEFORM_HALFWIDTH_MS = 1.0
WAVEFORM_SEED = 0

#%%

def _band_mask(img):
    """Mask of the cartoons' saturated blue coil band.

    Keyed on blue dominating both other channels rather than on an absolute
    blue level, so it ignores the drawings' black ink and grey pencil
    shading (where the three channels track each other) without needing a
    hand-tuned brightness cutoff.
    """
    r, g, b = (img[..., i].astype(np.int16) for i in range(3))
    return (b > 90) & (b - r > 50) & (b - g > 50)


def _load_cartoons(paths, pad_frac: float = 0.02, min_component_px: int = 100,
                   bottom: str = "ink"):
    """Read the cartoon JPEGs and trim white margin with a SHARED crop box.

    The drawings share one canvas and are ~93% pixel-identical: the same
    bird, drawn once, with a different apparatus added around it. Cropping
    each to its OWN ink bounding box would therefore scale them
    differently -- the screen drawing's ink extends further left and up, so
    its (larger) crop box shrinks more to fit the same cell, rendering the
    very same bird ~12% smaller than in the magnet drawing.

    So the union of every image's ink bbox is used as one common crop box,
    applied identically to all of them. Every returned array has the same
    shape, which keeps the shared bird at the same scale AND in the same
    relative position across panels, while still dropping the wide dead
    margin the raw canvas carries (cropping the pair together is purely a
    framing change; it cannot introduce a scale difference the way
    per-image cropping does). `pad_frac` re-pads by a fraction of the
    cropped size so strokes don't touch the edge.

    Isolated ink specks smaller than `min_component_px` (stray pen marks
    and scan dust) are ignored when measuring the box -- otherwise they
    hold dead margin open far past the drawing: a 24px dot alone kept 215
    columns of empty space on the right, and three specks below the tail
    kept ~80 rows below it. The threshold isn't finely tuned; every value
    from ~60 to ~500 yields the identical box here, since there's nothing
    of intermediate size outside the drawing. Only the BOX is measured
    this way -- the full image is what gets cropped and drawn, so specks
    inside the box still render; only ones outside it are cut.

    `bottom` picks where the crop ends. "ink" keeps the whole drawing.
    "band" instead cuts flush at the bottom of the blue coil band, dropping
    the wings and tail below it: the drawings are much taller than they are
    wide, and in a wide, short figure row they're limited by the row's
    HEIGHT, so shortening them is the only way to make them render larger
    and use more of the row's width. The band spans the full width of the
    bird, so cutting at its lowest row leaves a clean, deliberate-looking
    horizontal edge; no bottom padding is added there, which would
    reintroduce a sliver of tail below it.
    """
    imgs = []
    for path in paths:
        img = plt.imread(path)
        if img.dtype != np.uint8:  # matplotlib gives float [0, 1] for some formats
            img = (img * 255).astype(np.uint8)
        imgs.append(img)

    ink = np.zeros(imgs[0].shape[:2], dtype=bool)
    for img in imgs:
        if img.shape[:2] != ink.shape:  # a shared box is only meaningful on a shared canvas
            raise ValueError(f"cartoon canvases differ: {img.shape[:2]} vs {ink.shape}")
        ink |= img[..., :3].min(axis=-1) < 245
    # 8-connectivity, so a diagonal pen stroke counts as one component
    # rather than a string of separate single pixels.
    labels, n_labels = ndimage.label(ink, structure=np.ones((3, 3)))
    sizes = np.asarray(ndimage.sum(ink, labels, range(1, n_labels + 1)))
    kept = np.flatnonzero(sizes >= min_component_px) + 1
    solid = ink & np.isin(labels, kept)
    if not solid.any():  # everything is speck-sized -- fall back to all ink
        solid = ink

    rows = np.flatnonzero(solid.any(axis=1))
    cols = np.flatnonzero(solid.any(axis=0))
    if rows.size == 0 or cols.size == 0:  # all blank -- nothing to crop to
        return imgs

    pad_r = int(round(pad_frac * (rows[-1] - rows[0] + 1)))
    pad_c = int(round(pad_frac * (cols[-1] - cols[0] + 1)))
    r0 = max(rows[0] - pad_r, 0)
    r1 = min(rows[-1] + 1 + pad_r, ink.shape[0])
    c0 = max(cols[0] - pad_c, 0)
    c1 = min(cols[-1] + 1 + pad_c, ink.shape[1])
    if bottom == "band":
        band = np.zeros(ink.shape, dtype=bool)
        for img in imgs:
            band |= _band_mask(img)
        band_rows = np.flatnonzero(band.any(axis=1))
        if band_rows.size:
            r1 = min(band_rows[-1] + 1, r1)  # flush cut, no bottom pad
    elif bottom != "ink":
        raise ValueError(f"bottom must be 'ink' or 'band', got {bottom!r}")

    return [img[r0:r1, c0:c1] for img in imgs]


def load_data(data_dir: str):
    cfg = load_experiment(Path(__file__).parent.parent.parent / "experiments" / f"{EXPERIMENT}.yml")
    io_r, nwbfile = nwb_io.read_nwbfile(str(Path(data_dir) / f"{EXPERIMENT}.nwb"))
    modulation_df = nwb_io.build_modulation_frame(nwbfile, good_only=cfg.good)
    fourier_df = nwb_io.read_fourier_results_as_full_fourier_df(nwbfile)
    group_df, unit_df = nwb_io.read_fourier_group_and_unit_tables(nwbfile)
    io_r.close()
    return modulation_df, fourier_df, group_df, unit_df


def plot_fig1_composite(modulation_df, fourier_df, group_df, unit_df, out_dir: Path,
                        out_name: str = "Fig1.pdf", cartoon_bottom: str = "ink"):
    # Fig1_NPIX_data only reads unitrow.cluster_id (not .ch) -- no NAS-backed
    # cluster_info.tsv lookup needed here, just the cluster id itself.
    unitrow = pd.Series({"cluster_id": CLUSTER_ID})

    mag_allspks, mag_spks, (fou0, fou_alt, ff_alt, exemplar_NFC), _ = \
        statistics.Fig1_NPIX_data(modulation_df, MAG_CONTINGENCY, unitrow, MAG_FREQ, group_df, unit_df)
    vis_allspks, vis_spks, (vis_fou0, vis_fou_alt, vis_ff_alt, exemplar_NFC_vis), _ = \
        statistics.Fig1_NPIX_data(modulation_df, VIS_CONTINGENCY, unitrow, VIS_FREQ, group_df, unit_df)

    # Pre-extracted raw-voltage snippets (see fig1_extract_raw_snippets.py) --
    # the only NAS-derived inputs to this figure, cached locally so this
    # script itself needs no NAS access.
    raw_dir = Path(FP.DATA_DIR) / "fig1_raw"
    mag_trace = np.load(raw_dir / "mag_trace.npy")
    vis_trace = np.load(raw_dir / "vis_trace.npy")
    waveforms = np.load(raw_dir / "vis_waveforms.npy")  # (N_WAVEFORMS, n_samples)

    font = {"family": FP.FONT_FAMILY, "size": FP.FS_BODY}
    matplotlib.rc("font", **font)

    # Three stacked rows: the two stimulus cartoons side by side; mag/vis
    # rasters + spectra (2 columns); and the dist+ECDF pairs (mag pair then
    # vis pair) at the bottom -- spectra sit next to their own raster, and
    # each NFC distribution sits next to its own ECDF-deviation plot, so
    # nothing needs a whole row to itself just to show 1-2 panels.
    fig = plt.figure(figsize=FP.FIGSIZE_FIG1_COMPOSITE, tight_layout=True)
    # The top (cartoon) row is given more room, and the two busier rows
    # below it correspondingly less -- the cartoons aren't cramped by
    # content the way the other two rows are, so they can afford to grow.
    # Explicit spacer rows with hspace=0, rather than one uniform hspace --
    # GridSpec's hspace is a single figure-wide value, but the cartoon row
    # needs far less air beneath it (nothing hangs below the drawings) than
    # the trace/raster row does (whose "Phase (rad)" axis labels would
    # otherwise collide with the E/F panel labels below them).
    outer_gs = gridspec.GridSpec(5, 1, left=0, bottom=0, right=1, top=1,
                                  height_ratios=[0.81, 0.10, 1.04, 0.40, 0.68],
                                  hspace=0)

    # Top row: the two stimulus-configuration cartoons side by side, each
    # sitting directly above the data column it describes -- magnet (left,
    # over the magnetic column) and grating screen (right, over the visual
    # column). The same
    # width_ratios as bc_gs below, so each cartoon is horizontally centered
    # on its own column rather than on a naive half of the figure.
    cartoon_gs = outer_gs[0].subgridspec(1, 3, width_ratios=[1, SPACER_COL_WIDTH, 1],
                                    wspace=COL_WSPACE)
    # Each drawing goes in an inset filling a blank full-cell container
    # (same pattern as waveform_cell_ax below): imshow's equal aspect
    # shrinks the axes box itself to the image, which would drag a panel
    # label annotated in axes coordinates inward with it -- the container
    # keeps its full cell width, so panel A's label stays aligned with
    # panel B's directly below it.
    cartoon_mag_cell = fig.add_subplot(cartoon_gs[0, 0])
    cartoon_vis_cell = fig.add_subplot(cartoon_gs[0, 2])
    cartoon_mag_cell.axis("off")
    cartoon_vis_cell.axis("off")
    cartoon_mag_ax = cartoon_mag_cell.inset_axes([0, 0, 1, 1])
    cartoon_vis_ax = cartoon_vis_cell.inset_axes([0, 0, 1, 1])

    # A narrow middle column between the magnetic and visual traces holds the average-waveform
    # (top) and phase-colorwheel (bottom) legends, stacked -- keeping them
    # off of either raw-trace panel's own data instead of overlaid on top of
    # it.
    bc_gs = outer_gs[2].subgridspec(1, 3, width_ratios=[1, SPACER_COL_WIDTH, 1],
                               wspace=COL_WSPACE)

    # Each of the two stimulus columns is itself 2 stacked rows: the raw trace (with its own
    # embedded raster/phasors, via raw_NPIX) on top, and the phase raster +
    # Fourier spectrum side by side below it -- the raster's the SAME spikes
    # folded onto stimulus phase, and the spectrum is the Fourier transform
    # of those same spikes, so the two sit next to each other as a single
    # visual argument: raw trace -> periodicity -> spectrum. The raster
    # covers every spike that went into that Fourier fit/NFC (the whole
    # recording), not just the ones visible in the raw trace's short window
    # above it.
    mag_col_gs = bc_gs[0, 0].subgridspec(2, 1, height_ratios=[1.1, 1.0], hspace=0.15)
    vis_col_gs = bc_gs[0, 2].subgridspec(2, 1, height_ratios=[1.1, 1.0], hspace=0.15)

    mag_raw_ax = fig.add_subplot(mag_col_gs[0, 0])
    mag_bottom_gs = mag_col_gs[1, 0].subgridspec(1, 2, width_ratios=[1.5, 1], wspace=0.62)
    mag_raster_ax = fig.add_subplot(mag_bottom_gs[0, 0])
    mag_spectra_ax = fig.add_subplot(mag_bottom_gs[0, 1])

    # sharey with mag_raw_ax: both panels are plotted mean-subtracted (not
    # independently min-max-normalized to [0, 1], which would erase any real
    # amplitude difference between them) below, so a shared y-axis is what
    # makes the raw traces honestly comparable.
    vis_raw_ax = fig.add_subplot(vis_col_gs[0, 0], sharey=mag_raw_ax)
    vis_bottom_gs = vis_col_gs[1, 0].subgridspec(1, 2, width_ratios=[1.5, 1], wspace=0.62)
    vis_raster_ax = fig.add_subplot(vis_bottom_gs[0, 0])
    vis_spectra_ax = fig.add_subplot(vis_bottom_gs[0, 1])

    # Waveform and phase colorwheel are both confined to a cell matching
    # mag_col_gs/vis_col_gs's own top (raw-trace) row -- so the waveform is
    # top-aligned with the raw-trace titles, and the wheel sits directly below it,
    # instead of the wheel being pushed all the way down to the bottom of
    # the whole raw-trace block. The lower cell (matching the raster/spectra row)
    # is left empty.
    legend_gs = bc_gs[0, 1].subgridspec(2, 1, height_ratios=[1.1, 1.0], hspace=0.15)
    legend_top_gs = legend_gs[0, 0].subgridspec(2, 1, height_ratios=[1, 1], hspace=0.15)
    # Narrower and taller than its own cell (via inset_axes on a blank
    # full-cell container), and nudged up slightly (y0 > 0) -- a plain
    # fig.add_subplot here would stretch to fill the whole (wide, short)
    # cell, which is the wrong aspect for a waveform trace.
    waveform_cell_ax = fig.add_subplot(legend_top_gs[0, 0])
    waveform_cell_ax.axis("off")
    waveform_ax = waveform_cell_ax.inset_axes([0.25, 0.1 + LEGEND_LIFT, 0.5, 1.15])
    # Same blank-container + inset pattern as the waveform above, purely so
    # the wheel can be lifted by LEGEND_LIFT -- a plain add_subplot would be
    # pinned to its own cell.
    wheel_cell_ax = fig.add_subplot(legend_top_gs[1, 0])
    wheel_cell_ax.axis("off")
    wheel_ax = wheel_cell_ax.inset_axes([0, LEGEND_LIFT, 1, 1])

    # Bottom row: each NFC distribution and its own ECDF-deviation plot
    # share a single panel (the ECDF as a small inset in the dist panel's
    # otherwise-empty upper-right corner) -- mag then vis -- rather than 4
    # separate axes (tried 2026-09-02, reverted -- 2 panels read cleaner
    # than 4 smaller ones here).
    de_hi_gs = outer_gs[4].subgridspec(1, 2, wspace=0.22)
    mag_dist_ax = fig.add_subplot(de_hi_gs[0, 0])
    vis_dist_ax = fig.add_subplot(de_hi_gs[0, 1])

    # ── Plot Row 1 ────────────────────────────────────────────────────────────
    # Stimulus-configuration cartoons. imshow's default aspect="equal"
    # keeps each drawing undistorted, so it shrinks to fit the row height
    # and centers itself in its own (wider) cell rather than being
    # stretched to fill it.
    # Loaded as a pair so both get the same crop box -- see _load_cartoons
    # for why per-image cropping would rescale the shared bird.
    # Titled on the inset (not the blank container) axes so each title sits
    # directly above its own drawing -- imshow's equal aspect shrinks the
    # inset's box down to the image, so a container-level title would float
    # a variable gap above whichever cartoon ended up shorter.
    for _ax, _img, _title in zip((cartoon_mag_ax, cartoon_vis_ax),
                                 _load_cartoons((CARTOON_MAG_PATH, CARTOON_VIS_PATH),
                                                bottom=cartoon_bottom),
                                 ("Magnetic stimulation", "Visual stimulation")):
        _ax.imshow(_img, interpolation="antialiased")
        _ax.axis("off")
        _ax.set_title(_title, fontsize=FP.FS_TITLE)

    # Mean-subtract only (no per-trace min-max rescaling) so panel B's two traces'
    # shared y-axis (see sharey above) reflects each trace's real amplitude
    # relative to the other, rather than both being independently stretched
    # to fill [0, 1].
    mean_subtract = lambda arr: arr - np.mean(arr)

    # Mag raw NPIX (null result) -- scale bar shows one stimulus period (1/freq)
    statistics.raw_NPIX(mag_raw_ax, None, mag_spks, None, MAG_WINDOW, MAG_FREQ,
                         label=1 / MAG_FREQ, trace=mag_trace, spike_sr=MAG_TRACE_SR,
                         raster_lw=RASTER_LW, phase_cmap=PHASE_CMAP, normalize=mean_subtract,
                         stem_scale=ARROW_STEM_SCALE, scalebar_frac=0.5)
    mag_raw_ax.set_title(f"Voltage trace during magnetic stimulation at {MAG_FREQ:g} Hz",
                          fontsize=FP.FS_TITLE)

    # Visual raw NPIX (positive result) -- same unit, same primitive as the mag panel
    statistics.raw_NPIX(vis_raw_ax, None, vis_spks, None, VIS_WINDOW, VIS_FREQ,
                         label=1 / VIS_FREQ, trace=vis_trace, spike_sr=VIS_TRACE_SR,
                         raster_lw=RASTER_LW, phase_cmap=PHASE_CMAP, normalize=mean_subtract,
                         stem_scale=ARROW_STEM_SCALE, scalebar_frac=0.5,
                         raster_color=FP.COLOR_VIS)
    vis_raw_ax.set_title(f"Voltage trace during visual stimulation at {VIS_FREQ:g} Hz",
                          fontsize=FP.FS_TITLE)

    # Phase raster: ALL spikes that actually went into this unit's Fourier
    # fit/NFC at MAG_FREQ/VIS_FREQ (the whole recording, via mag_spks/
    # vis_spks -- not just the handful visible in the raw trace's short
    # window above), folded onto stimulus phase (x axis in radians, one row
    # per stimulus cycle) -- makes explicit what that Fourier fit is
    # actually testing for (a stimulus-locked unit's ticks line up in a
    # vertical band; an unlocked one scatters).
    #
    # Window starts at the FIRST SPIKE's own cycle boundary, not at t=0 --
    # this unit doesn't fire at all for a while after the recording starts,
    # so anchoring at 0 left ~100-200 entirely empty rows at the top of the
    # raster for no informative reason. Starting at
    # floor(first_spike*freq)/freq -- an exact integer number of stimulus
    # periods after 0 -- crops that dead stretch without shifting any
    # spike's phase (phase is computed mod period, and shifting the
    # reference point by a whole number of periods changes nothing).
    mag_start_t = np.floor(np.min(mag_spks) * MAG_FREQ) / MAG_FREQ
    vis_start_t = np.floor(np.min(vis_spks) * VIS_FREQ) / VIS_FREQ
    mag_full_window = (mag_start_t, float(np.max(mag_spks)) + 1e-6)
    vis_full_window = (vis_start_t, float(np.max(vis_spks)) + 1e-6)

    statistics.plot_phase_raster(mag_raster_ax, mag_spks, mag_full_window, MAG_FREQ,
                                  color=FP.COLOR_MAG, phase_cmap=PHASE_CMAP,
                                  pad_x=RASTER_PAD_X, pad_y=RASTER_PAD_Y)
    mag_raster_ax.set_title("Spike phases", fontsize=FP.FS_TITLE)
    mag_raster_ax.spines["top"].set_visible(False)
    mag_raster_ax.spines["right"].set_visible(False)
    # Smoothed firing-rate PSTH overlay -- not part of the actual Fourier/NFC
    # computation, just a visual aid for the trend across phase -- on its
    # own grey twin y-axis so it reads as secondary to the raster itself.
    mag_psth_ax = statistics.plot_smoothed_phase_psth(
        mag_raster_ax, mag_spks, mag_full_window, MAG_FREQ, color="grey")

    statistics.plot_phase_raster(vis_raster_ax, vis_spks, vis_full_window, VIS_FREQ,
                                  color=FP.COLOR_VIS, phase_cmap=PHASE_CMAP,
                                  pad_x=RASTER_PAD_X, pad_y=RASTER_PAD_Y)
    vis_raster_ax.set_title("Spike phases", fontsize=FP.FS_TITLE)
    vis_raster_ax.spines["top"].set_visible(False)
    vis_raster_ax.spines["right"].set_visible(False)
    vis_psth_ax = statistics.plot_smoothed_phase_psth(
        vis_raster_ax, vis_spks, vis_full_window, VIS_FREQ, color="grey")

    # The width between each raster and its spectrum is set by two FACING
    # axis decorations -- the raster's PSTH twin axis on the right and the
    # spectrum's "Amplitude" axis on the left -- not by empty space, so the
    # panels can only be brought closer by shrinking those. The PSTH axis is
    # already deliberately secondary (grey, a visual aid rather than part of
    # the Fourier computation), so it takes the smaller legend font; the
    # spectrum keeps body-size labels and just loses its tick padding.
    for _psth_ax in (mag_psth_ax, vis_psth_ax):
        _psth_ax.set_ylabel("PSTH (Hz)", color="grey", fontsize=FP.FS_LEGEND, labelpad=1)
        _psth_ax.tick_params(axis="y", labelsize=FP.FS_LEGEND, pad=1)
        # Headroom above the curve plus a matching gap below (see PSTH_PAD_Y),
        # so a trough that reaches 0 Hz isn't drawn on top of the raster's
        # bottom spine. Each row keeps its OWN rate scale, unlike Fig4A's
        # three panels, which share one: those are a single unit at three
        # modulation amplitudes, where the growth of the curve between them
        # is the point, whereas these two rows are different stimuli whose
        # absolute rates aren't meant to be read against each other.
        _psth_max = _psth_ax.get_ylim()[1]
        _psth_ax.set_ylim(-_psth_max * PSTH_PAD_Y, _psth_max * 1.05)
        # The negative bottom limit is padding, not data -- drop any tick the
        # locator puts below 0, which would read as a negative firing rate.
        _psth_ax.set_yticks([t for t in _psth_ax.get_yticks()
                             if 0 <= t <= _psth_max * 1.05])

    # ── Plot Row 2: Magnetic stimulation (null) ──────────────────────────────
    statistics.plot_spectrum(mag_spectra_ax, fou_alt.flatten(), ff_alt, MAG_FREQ, fou0, legend=False,
                              dot_color=FP.COLOR_MAG, stem_color="black", sigma_color="gray")
    mag_spectra_ax.set_title("Fourier coefficients", fontsize=FP.FS_TITLE)
    mag_spectra_ax.set_ylabel("Magnitude", labelpad=1)
    mag_spectra_ax.tick_params(axis="y", pad=1)
    mag_spectra_ax.set_xlabel("Freq (Hz)")
    mag_spectra_ax.spines["top"].set_visible(False)
    mag_spectra_ax.spines["right"].set_visible(False)
    statistics.boundary_ticks(mag_spectra_ax, y=False)

    statistics.draw_hist(fourier_df.loc[fourier_df.rec == MAG_CONTINGENCY, "NFC"], mag_dist_ax, xlim=9,
                         inset=True, bar_color=FP.COLOR_MAG, legend_fontsize=FP.FS_LEGEND)
    # Triangle sits just above the x-axis, pointing down at it (blended
    # transform: x in data coords, y in axes-fraction) -- marks the
    # exemplar's NFC position along the x-axis (2026-09-02: was an arrow
    # annotation below the axis, then an upward triangle below the axis;
    # now a downward triangle above it, half-transparent so it doesn't
    # compete with any bar/curve it happens to sit over).
    mag_xaxis_trans = mag_dist_ax.get_xaxis_transform()
    mag_dist_ax.plot(exemplar_NFC, 0.06, marker="v", color="black", alpha=0.5, markersize=8,
                     transform=mag_xaxis_trans, clip_on=False, zorder=5)
    statistics.boundary_ticks(mag_dist_ax, yprec=1)
    statistics.nestle_labels(mag_dist_ax, x_offset=-0.05, y_offset=-0.05)

    # ── Plot Row 3: Visual gratings (positive) ───────────────────────────────
    statistics.plot_spectrum(vis_spectra_ax, vis_fou_alt.flatten(), vis_ff_alt, VIS_FREQ, vis_fou0, legend=False,
                              dot_color=FP.COLOR_VIS, stem_color="black", sigma_color="gray")
    vis_spectra_ax.set_title("Fourier coefficients", fontsize=FP.FS_TITLE)
    vis_spectra_ax.set_ylabel("Magnitude", labelpad=1)
    vis_spectra_ax.tick_params(axis="y", pad=1)
    vis_spectra_ax.set_xlabel("Freq (Hz)")
    vis_spectra_ax.spines["top"].set_visible(False)
    vis_spectra_ax.spines["right"].set_visible(False)
    statistics.boundary_ticks(vis_spectra_ax, y=False)

    # Shared y-axis (Magnitude) between the two spectra -- makes their
    # scales directly comparable, even though it squashes E's much smaller
    # scatter/stem (mag's |c_s| is far smaller than vis's) down near the
    # bottom of the shared range.
    spectra_ylim = (0, max(mag_spectra_ax.get_ylim()[1], vis_spectra_ax.get_ylim()[1]))
    mag_spectra_ax.set_ylim(spectra_ylim)
    vis_spectra_ax.set_ylim(spectra_ylim)

    statistics.draw_hist(fourier_df.loc[fourier_df.rec == VIS_CONTINGENCY, "NFC"],
                         vis_dist_ax, xlim=12, inset=True, bar_color=FP.COLOR_VIS,
                         legend_fontsize=FP.FS_LEGEND)
    # exemplar_NFC_vis (~7.79) sits out in this population's right tail --
    # consistent with this being a deliberately strong (tightly phase-
    # concentrated), not just barely-significant, exemplar (see module
    # docstring), on top of an already strong "positive control" population
    # (22% of units significant at this orientation). Triangle above the
    # x-axis, same as mag_dist_ax -- see that marker's comment.
    vis_xaxis_trans = vis_dist_ax.get_xaxis_transform()
    vis_dist_ax.plot(exemplar_NFC_vis, 0.06, marker="v", color="black", alpha=0.5, markersize=8,
                     transform=vis_xaxis_trans, clip_on=False, zorder=5)
    statistics.boundary_ticks(vis_dist_ax, yprec=1)
    statistics.nestle_labels(vis_dist_ax, x_offset=-0.05, y_offset=-0.05)

    # ── Kolmogorov-Smirnov diagnostic plot ────────────────────────────────────
    # Each ECDF-deviation curve is now an inset within its own dist panel
    # (mag_dist_ax/vis_dist_ax's otherwise-empty upper-right corner) rather
    # than a separate full-width axes -- the frequency/modality info that
    # used to live in each curve's own "lonely" one-line legend now lives in
    # the panel's title instead, so no legend is needed at all.
    mag_NFC = fourier_df.loc[fourier_df.rec == MAG_CONTINGENCY, "NFC"].values
    vis_NFC = fourier_df.loc[fourier_df.rec == VIS_CONTINGENCY, "NFC"].values

    # Convert NFC to p-values
    mag_pvals = 1 - normalized_Fourier_CDF(mag_NFC)
    vis_pvals = 1 - normalized_Fourier_CDF(vis_NFC)

    # Same conversion, applied to the single exemplar unit's own NFC -- so its
    # position along the ECDF-deviation curve's own x-axis (p-value) can be
    # marked explicitly, the same way the arrow below mag_dist_ax/vis_dist_ax
    # already marks its NFC on the histogram's x-axis.
    exemplar_p_mag = float(1 - normalized_Fourier_CDF(np.array([exemplar_NFC]))[0])
    exemplar_p_vis = float(1 - normalized_Fourier_CDF(np.array([exemplar_NFC_vis]))[0])

    def _fmt_p(p):
        return "p<0.001" if p < 0.001 else f"p={p:.2g}"

    ecdf_mag_ax = mag_dist_ax.inset_axes([0.52, 0.48, 0.45, 0.44])
    ecdf_vis_ax = vis_dist_ax.inset_axes([0.52, 0.48, 0.45, 0.44])

    # Plot mag K-S diagnostic: ECDF(x) - x with 95% CI
    mag_x, mag_lower, mag_upper = bootstrap_ecdf_band(mag_pvals, alpha=0.05)
    # Empirical ECDF at sorted points
    mag_ecdf = (np.arange(1, len(mag_pvals) + 1)) / len(mag_pvals)
    # K-S deviation: empirical ECDF minus theoretical (uniform) CDF
    mag_ks_dev = mag_ecdf - mag_x
    mag_ks_lower = mag_lower - mag_x
    mag_ks_upper = mag_upper - mag_x
    ecdf_mag_ax.plot(mag_x, mag_ks_dev, color=FP.COLOR_MAG, linewidth=FP.LW_TRACE)
    ecdf_mag_ax.fill_between(mag_x, mag_ks_lower, mag_ks_upper, color=FP.COLOR_MAG, alpha=FP.ALPHA_CONFIDENCE)
    ecdf_mag_ax.axhline(0, color=FP.COLOR_NULL, linestyle="--", linewidth=FP.LW_REFERENCE, alpha=0.6)
    # Exemplar unit's own p-value, marked the same way across both ECDF
    # panels -- a downward triangle above the x-axis, same convention as
    # mag_dist_ax/vis_dist_ax's own exemplar-NFC marker above (2026-09-02:
    # was a vertical line, then an upward triangle below the axis).
    ecdf_mag_xaxis_trans = ecdf_mag_ax.get_xaxis_transform()
    ecdf_mag_ax.plot(exemplar_p_mag, 0.09, marker="v", color="black", alpha=0.5, markersize=6,
                     transform=ecdf_mag_xaxis_trans, clip_on=False, zorder=5)
    ecdf_mag_ax.annotate(_fmt_p(exemplar_p_mag), xy=(exemplar_p_mag, 1.0),
                         xycoords=("data", "axes fraction"), xytext=(2, -2),
                         textcoords="offset points", ha="left", va="top",
                         fontsize=FP.FS_LEGEND, color="black")
    ecdf_mag_ax.set_xlabel("p-value", fontsize=FP.FS_LEGEND, labelpad=1)
    ecdf_mag_ax.set_ylabel("ECDF dev.", fontsize=FP.FS_LEGEND, labelpad=1)
    ecdf_mag_ax.set_xlim((0, 1))
    ecdf_mag_ax.tick_params(labelsize=FP.FS_LEGEND, pad=1)
    statistics.boundary_ticks(ecdf_mag_ax, y=False)
    statistics.nestle_labels(ecdf_mag_ax, y=False, x_offset=-0.1)
    ecdf_mag_ax.spines["top"].set_visible(False)
    ecdf_mag_ax.spines["right"].set_visible(False)

    # Plot visual K-S diagnostic: ECDF(x) - x with 95% CI
    vis_x, vis_lower, vis_upper = bootstrap_ecdf_band(vis_pvals, alpha=0.05)
    # Empirical ECDF at sorted points
    vis_ecdf = (np.arange(1, len(vis_pvals) + 1)) / len(vis_pvals)
    # K-S deviation: empirical ECDF minus theoretical (uniform) CDF
    vis_ks_dev = vis_ecdf - vis_x
    vis_ks_lower = vis_lower - vis_x
    vis_ks_upper = vis_upper - vis_x
    ecdf_vis_ax.plot(vis_x, vis_ks_dev, color=FP.COLOR_VIS, linewidth=FP.LW_TRACE)
    ecdf_vis_ax.fill_between(vis_x, vis_ks_lower, vis_ks_upper, color=FP.COLOR_VIS, alpha=FP.ALPHA_CONFIDENCE)
    ecdf_vis_ax.axhline(0, color=FP.COLOR_NULL, linestyle="--", linewidth=FP.LW_REFERENCE, alpha=0.6)
    # exemplar_p_vis is tiny (~1e-14, NFC=7.79) -- right at the left edge of
    # the (0,1) x-axis, same place its own bar sits in vis_dist_ax's ECDF
    # curve (see exemplar_p_mag's comment above for why/how this is marked).
    ecdf_vis_xaxis_trans = ecdf_vis_ax.get_xaxis_transform()
    ecdf_vis_ax.plot(exemplar_p_vis, 0.09, marker="v", color="black", alpha=0.5, markersize=6,
                     transform=ecdf_vis_xaxis_trans, clip_on=False, zorder=5)
    ecdf_vis_ax.annotate(_fmt_p(exemplar_p_vis), xy=(exemplar_p_vis, 1.0),
                         xycoords=("data", "axes fraction"), xytext=(2, -2),
                         textcoords="offset points", ha="left", va="top",
                         fontsize=FP.FS_LEGEND, color="black")
    ecdf_vis_ax.set_xlabel("p-value", fontsize=FP.FS_LEGEND, labelpad=1)
    ecdf_vis_ax.set_ylabel("ECDF dev.", fontsize=FP.FS_LEGEND, labelpad=1)
    ecdf_vis_ax.set_xlim((0, 1))
    ecdf_vis_ax.tick_params(labelsize=FP.FS_LEGEND, pad=1)
    statistics.boundary_ticks(ecdf_vis_ax, y=False)
    statistics.nestle_labels(ecdf_vis_ax, y=False, x_offset=-0.1)
    ecdf_vis_ax.spines["top"].set_visible(False)
    ecdf_vis_ax.spines["right"].set_visible(False)

    # ── Average spike-waveform + phase colorwheel legend, stacked in the
    # narrow column between panel B's two traces (see legend_gs above) -- own
    # (blank) axes rather than insets over either raw-trace panel, so
    # neither needs an opaque backdrop to keep trace data from showing
    # through their titles/tick labels. The wheel is the smaller of the two,
    # so its labels shrink to match (see waveform_ax's own inset_axes bounds
    # above for its narrower/taller sizing).
    statistics.plot_phase_colorwheel(wheel_ax, cmap=PHASE_CMAP, angle_unit="radians", fontsize=7)

    n_samples = waveforms.shape[1]
    half_width_samples = n_samples // 2
    t_ms = (np.arange(n_samples) - half_width_samples) / VIS_TRACE_SR * 1000
    for wf in waveforms:
        waveform_ax.plot(t_ms, wf, color="grey", linewidth=0.3, alpha=0.15)
    waveform_ax.plot(t_ms, waveforms.mean(axis=0), color="k", linewidth=1)
    waveform_ax.axis("off")

    fig.subplots_adjust(bottom=0, top=1, left=0, right=1)
    fig.canvas.draw()

    # ── Panel labels ──────────────────────────────────────────────────────────
    _label_kw = dict(fontfamily="arial", fontsize=11, weight="bold")
    # Reading order left-to-right, top-to-bottom. Each of A, B, C, D covers a
    # PAIR of axes, labelled once on the pair's leftmost member: the two
    # stimulus cartoons (A), the two raw voltage traces (B), and each
    # column's own phase raster + spectrum (C magnetic, D visual). Each pair
    # is one panel -- either the same view under two stimulus conditions, or
    # one argument made in two steps (fold the spikes onto stimulus phase,
    # then Fourier-transform them) -- rather than two independently
    # referenced panels, and every member carries its own descriptive title.
    # E and F are the two NFC distributions (each with its own ECDF inset).
    #
    # x is a per-COLUMN figure coordinate, not each axes' own fraction: the
    # axes stacked in a column have different widths (a raw voltage trace
    # spans the whole column, a phase raster only the left ~60% of it), so a
    # constant axes-fraction offset lands their labels at visibly different
    # x. Taking each column's leftmost axes edge and stepping a fixed
    # figure-space LABEL_DX left of it puts A/B/C/E on one vertical line and
    # D/F on another. y stays in each axes' own fraction (blended transform
    # below), so each label keeps whatever vertical offset clears its own
    # title.
    LABEL_DX = 0.05
    left_x = min(a.get_position().x0 for a in
                 (cartoon_mag_cell, mag_raw_ax, mag_raster_ax, mag_dist_ax)) - LABEL_DX
    right_x = min(a.get_position().x0 for a in (vis_raster_ax, vis_dist_ax)) - LABEL_DX

    def _panel_label(ax, text, x_fig, y_axes):
        ax.annotate(text, xy=(x_fig, y_axes), annotation_clip=False, **_label_kw,
                     xycoords=matplotlib.transforms.blended_transform_factory(
                         fig.transFigure, ax.transAxes))

    _panel_label(cartoon_mag_cell, "A", left_x, 1.0)
    _panel_label(mag_raw_ax, "B", left_x, 1.1)
    _panel_label(mag_raster_ax, "C", left_x, 1.12)
    _panel_label(vis_raster_ax, "D", right_x, 1.12)
    _panel_label(mag_dist_ax, "E", left_x, 1.1)
    _panel_label(vis_dist_ax, "F", right_x, 1.1)
    out_path = out_dir / out_name
    fig.savefig(out_path, bbox_inches="tight", dpi=FP.DPI)
    print(f"Saved {out_path}")
    if not in_notebook:
        plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="Generate Fig 1 (composite NPIX null + positive + ECDFs)")
    parser.add_argument("--out-dir", default=FP.OUT_DIR, help="Output directory for PDFs")
    parser.add_argument("--data-dir", default=FP.DATA_DIR, help="Directory containing pipeline output pickles")
    args = parser.parse_args([] if in_notebook else None)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Loading NPIX data...")
    modulation_df, fourier_df, group_df, unit_df = load_data(args.data_dir)
    plot_fig1_composite(modulation_df, fourier_df, group_df, unit_df, out_dir)
    # Same figure, cartoons cut off at the bottom of the coil band -- see
    # _load_cartoons' `bottom` for why that makes them render wider.
    plot_fig1_composite(modulation_df, fourier_df, group_df, unit_df, out_dir,
                        out_name="Fig1_wide.pdf", cartoon_bottom="band")


if __name__ == "__main__":
    if in_notebook:
        # Programmatic equivalent of the `%config` IPython magic -- same
        # effect (retina figure format for inline display), but doesn't
        # require IPython's magic-command preprocessing, so this file stays
        # runnable via plain `python fig1.py` too, not just `%run` inside a
        # live IPython/Jupyter session.
        get_ipython().run_line_magic("config", "InlineBackend.figure_format = 'retina'")
    main()
