"""Fig 1 — composite: NPIX null result + NPIX positive result + spectra + p-value ECDFs.

Both the null (magnetic stimulus) and positive (visual gratings) panels come from
the SAME exemplar unit (cluster 540, experiment 20230413_secondsite, Pigeon W25R,
hippocampus) -- it's non-significant across all 7 of its own magnetic-stimulus
trials (and both white-noise recs), yet significant at 3 of its 8 visual-gratings
orientations (all 3Hz: 45 degrees p<0.0001 NFC=7.79; 315 degrees p<0.0001 NFC=4.52;
270 degrees p=0.019 NFC=2.84). Using one neuron/session/probe for both panels is
a stronger story than two different units from two different sessions: it
preempts the "maybe that channel just wasn't picking up signal" critique, since
the same channel clearly does pick up signal (for the visual grating) but just
doesn't respond to the magnet.

This unit fires only modestly (~1.7-3.1Hz) -- a deliberate change from an
earlier iteration of this worktree (cluster 566, same experiment, ~20-27Hz),
which turned out to be a mistake for this figure's purpose despite satisfying
an earlier "prefer higher firing" request. The phasor-arrow colors in panels
B/C encode phase *relative to each panel's own window*, so a genuinely
stimulus-locked spike train should show arrows clustering on one dominant hue,
not a rainbow -- that's the whole visual point of the colorwheel. Cluster 566
was significant (p=0.0035) purely because of its very high spike count (n=1794
at 45 degrees); its actual phase concentration (circular resultant length
R=0.075) was tiny, so its arrows in panels B/C looked like uniform noise even
across 6 stimulus cycles -- a real "just significant, not astronomical" effect
can still be too visually diffuse to see by eye. Cluster 540, despite far fewer
spikes, has R=0.457 at 45 degrees (the tightest concentration found among this
experiment's null-to-mag, significant-to-visual candidates) -- its panel-C
arrows visibly cluster on warm hues (red/orange/yellow) across 15 stimulus
cycles, while panel B's arrows (mag, null) stay scattered across the whole
wheel. Firing rate and phase concentration turned out to trade off against each
other among this experiment's candidate units; satisfying "see a pattern by
eye" took priority here since that was the more recent, more specific request.

Choice of experiment matters here as much as choice of unit: unlike
20230414_firstsite (a previous iteration of this same worktree, cluster 100),
whose visual-gratings *population* only had 4.9-12.1% of units significant at
any given orientation -- a fairly weak "positive control" for the population
histogram in panel H -- 20230413_secondsite's visual_movinggratings3Hz
population has up to 22.0% of units significant at a single orientation (45
or 90 degrees), while its own mag recs stay near the ~2-9% chance rate. That
makes the population-level story in panels D-I honestly stronger, not just
the single-exemplar story in panels B/C. (Population significance fractions
per rec were scanned across all NPIX experiments with visual-gratings data;
see git history / session notes for the full comparison table.)

The best null (Mag3) and best positive (visual_movinggratings3Hz, orientation
45) conditions are both at 3Hz, so this comparison isolates modality rather
than confounding it with frequency.

Phasor arrows in panels B/C are colored by phase (cyclic `hsv` colormap, 0 to
one stimulus period) -- see the colorwheel legend inset in panel H.

A previous version of this figure (pipeline/manuscript/fig1_auditory.py)
instead compared magnetic stimulation to the 0.8Hz auditory white-noise
condition, using a different exemplar unit (cluster 106/experiment 20230415)
-- kept alongside this one for reference/comparison, not regenerated by
default. See its docstring for that version's own rationale.

Requires pipeline outputs:
  data/20230413_secondsite.nwb

Requires pre-extracted raw-voltage snippets (see fig1_extract_raw_snippets.py,
which is the only piece of this figure that needs NAS access):
  data/fig1_raw/mag_trace.npy
  data/fig1_raw/vis_trace.npy
  data/fig1_raw/vis_waveforms.npy

Usage:
    python pipeline/manuscript/fig1.py
    python pipeline/manuscript/fig1.py --out-dir figs/paper
"""
#%%
import argparse
from pathlib import Path

# Detect if running in Jupyter notebook (must do this before matplotlib.use)
try:
    from IPython import get_ipython
    in_notebook = get_ipython() is not None
except ImportError:
    in_notebook = False

import matplotlib
if not in_notebook:
    matplotlib.use("Agg")
import matplotlib.gridspec as gridspec
import matplotlib.patches as patches
import matplotlib.pyplot as plt
from matplotlib.colors import to_rgb
import numpy as np
import pandas as pd

import colorcet  # noqa: F401 -- import side effect registers "cet_*" colormaps with matplotlib
from ecdfbounds import bootstrap_ecdf_band
from magpyneto2 import statistics
from magpyneto2.statistics import normalized_Fourier_CDF
from pipeline import nwb_io
from pipeline.schema import load_experiment

import format_parameters as FP
#%%
# ── NAS paths (only used by fig1_extract_raw_snippets.py, not this script) ──
# (Unlike 20230414_firstsite's stale YAML `folder:` root in a previous
# iteration of this worktree, 20230413_secondsite's YAML root matches the
# actual NAS layout -- confirmed by listing the NAS directly.)
RAW_DATA_ROOT = r"\\datanas\family\data_raw\20230413\second_site"
AGGREGATED_PATH = r"\\datanas\family\data_aggregated\20230413_secondsite"

# ── Experiment / exemplar unit ────────────────────────────────────────────────
EXPERIMENT = "20230413_secondsite"
CLUSTER_ID = 540  # single unit, used for both the null and positive panels

MAG_CONTINGENCY = "2023-04-13_17-17-14_W25R_second_site_mag3"
MAG_FREQ = 3
# Non-significant (p=0.708, NFC=0.83) across this unit's mag3 trial -- of this
# unit's 7 null magnetic trials (p 0.374-0.916, all non-significant), this is
# the 3Hz one, chosen to match VIS_FREQ below so the null-vs-positive
# comparison isolates modality, not frequency.
# 15 cycles at 3Hz (period 1/3 s), not 1 -- with the phasor arrows now
# phase-colored, a single-cycle window is diagnostically uninformative: phase
# is computed as time-since-window-start mod period, which for a window no
# longer than one period trivially increases monotonically for ANY spike
# train (locked or not) since real time itself is monotonic. Only across
# multiple cycles can the reader actually compare whether phase/color repeats
# consistently cycle-to-cycle (locked) or drifts (not). This unit fires only
# ~1.7Hz here, so 15 cycles (5s) -- rather than a smaller cycle count -- is
# needed just to get a handful of spikes to look at; see the module docstring
# for why a sparser-but-tighter-locking unit was chosen over a denser one.
MAG_WINDOW = (49.143, 54.143)  # 5s = 15 cycles at 3Hz, ~8 spikes

# Visual gratings: recname is NOT orientation-split in the raw OpenEphys
# folder (all 8 orientations are one continuous recording, played back to
# back as 8 long single-orientation blocks) -- the "_45" suffix only exists
# in modulation_df/fourier_df's post-hoc orientation split.
VIS_CONTINGENCY = "2023-04-13_17-31-40_W25R_second_site_visual_movinggratings3Hz_45"
# The raw OpenEphys folder itself has no orientation suffix (only
# modulation_df/fourier_df's post-hoc orientation split does) -- used only by
# fig1_extract_raw_snippets.py to open the right raw folder.
VIS_RAW_RECNAME = "2023-04-13_17-31-40_W25R_second_site_visual_movinggratings3Hz"
VIS_FREQ = 3
# Best-NFC of this unit's 3 significant visual-gratings orientations (all
# 3Hz: 45 degrees p<0.0001 NFC=7.79, 315 degrees p<0.0001 NFC=4.52, 270
# degrees p=0.019 NFC=2.84) -- also the tightest phase concentration
# (circular resultant length R=0.457) found among this experiment's
# null-to-mag, visual-significant candidates, which is what actually makes
# the phasor-arrow colors in panel C visibly cluster by eye (see module
# docstring). Also 3Hz, matching MAG_FREQ, so the null-vs-positive comparison
# isolates modality, not frequency.
VIS_WINDOW = (91.789, 96.789)  # 5s = 15 cycles at 3Hz (see MAG_WINDOW comment), ~16 spikes

# Sampling rates for the pre-extracted raw-voltage snippets (see
# fig1_extract_raw_snippets.py, which prints these when it runs).
MAG_TRACE_SR = 30000
VIS_TRACE_SR = 30000

# Spike-raster tick linewidth, shared by both raw_NPIX panels (default is 2,
# which reads as visually heavy/blocky once many ticks are packed into a
# wider window).
RASTER_LW = 0.5

# Shrinks the phasor markers (via raw_NPIX's stem_scale) down from their
# full default size -- each spike still shows its phase as both a color and
# a pointing direction (the chevron shape), just smaller, so B/C read as a
# field of small phase markers rather than a dense cluster of larger ones.
ARROW_STEM_SCALE = 0.6

# Cyclic colormap for phase-coloring the phasor arrows in both raw_NPIX
# panels -- paired with a colorwheel legend (statistics.plot_phase_colorwheel)
# drawn between panels B and C. colorcet's CET_C6s (importing colorcet
# auto-registers it with matplotlib as "cet_CET_C6s") avoids "twilight"'s
# near-white anchor at phase=0, which would make arrows nearly invisible
# against this figure's white background.
PHASE_CMAP = "cet_CET_C6s"

# ── Average spike-waveform panel ──────────────────────────────────────────────
# 100 randomly-sampled raw waveforms (seeded for reproducibility) for this
# unit, drawn from the visual-gratings recording (larger spike count of the
# two: 204 vs 95 for the mag trial).
N_WAVEFORMS = 100
WAVEFORM_HALFWIDTH_MS = 1.0
WAVEFORM_SEED = 0

def _lighten(color, frac=0.55):
    """Blend `color` toward white by `frac` -- a lighter, still-opaque shade of
    the same hue, for the spectrum panels' "imaginary" series (paired with the
    full-saturation `color` for "real")."""
    r, g, b = to_rgb(color)
    return (r + (1 - r) * frac, g + (1 - g) * frac, b + (1 - b) * frac)


#%%

def load_data(data_dir: str):
    cfg = load_experiment(Path(__file__).parent.parent.parent / "experiments" / f"{EXPERIMENT}.yml")
    io_r, nwbfile = nwb_io.read_nwbfile(str(Path(data_dir) / f"{EXPERIMENT}.nwb"))
    modulation_df = nwb_io.build_modulation_frame(nwbfile, good_only=cfg.good)
    fourier_df = nwb_io.read_fourier_results_as_full_fourier_df(nwbfile)
    group_df, unit_df = nwb_io.read_fourier_group_and_unit_tables(nwbfile)
    io_r.close()
    return modulation_df, fourier_df, group_df, unit_df


def plot_fig1_composite(modulation_df, fourier_df, group_df, unit_df, out_dir: Path):
    # Fig1_NPIX_data only reads unitrow.cluster_id (not .ch) -- no NAS-backed
    # cluster_info.tsv lookup needed here, just the cluster id itself.
    unitrow = pd.Series({"cluster_id": CLUSTER_ID})

    mag_allspks, mag_spks, (fou0, fou_alt, ff_alt, exemplar_NFC), _ = \
        statistics.Fig1_NPIX_data(modulation_df, MAG_CONTINGENCY, unitrow, MAG_FREQ, group_df, unit_df)
    vis_allspks, vis_spks, (vis_fou0, vis_fou_alt, vis_ff_alt, exemplar_NFC_vis), _ = \
        statistics.Fig1_NPIX_data(modulation_df, VIS_CONTINGENCY, unitrow, VIS_FREQ, group_df, unit_df)

    # Pre-extracted raw-voltage snippets (see fig1_extract_raw_snippets.py) --
    # the only NAS-derived inputs to this figure, cached locally so this
    # script itself needs no NAS access.
    raw_dir = Path(FP.DATA_DIR) / "fig1_raw"
    mag_trace = np.load(raw_dir / "mag_trace.npy")
    vis_trace = np.load(raw_dir / "vis_trace.npy")
    waveforms = np.load(raw_dir / "vis_waveforms.npy")  # (N_WAVEFORMS, n_samples)

    font = {"family": FP.FONT_FAMILY, "size": FP.FS_BODY}
    matplotlib.rc("font", **font)

    # Four stacked rows: full-width cartoon, mag/vis raw traces (2 columns),
    # D/E/G/F all in a single row (4 columns, mag pair then vis pair), and
    # the split mag/vis ECDF (2 columns) at the bottom.
    fig = plt.figure(figsize=(FP.FIGSIZE_FIG1[0], FP.FIGSIZE_FIG1[1] * 1.45), tight_layout=True)
    outer_gs = gridspec.GridSpec(4, 1, left=0, bottom=0, right=1, top=1,
                                  height_ratios=[0.45, 1.3, 1.05, 1.15], hspace=0.5)

    cartoon_ax = fig.add_subplot(outer_gs[0])

    # A narrow middle column between B and C holds the phase colorwheel
    # (top) and waveform (bottom) legend, stacked -- keeping them off of
    # either raw-trace panel's own data instead of overlaid on top of it.
    bc_gs = outer_gs[1].subgridspec(1, 3, width_ratios=[1, 0.4, 1], wspace=0.08)
    mag_raw_ax = fig.add_subplot(bc_gs[0, 0])
    # sharey with mag_raw_ax: both panels are plotted mean-subtracted (not
    # independently min-max-normalized to [0, 1], which would erase any real
    # amplitude difference between them) below, so a shared y-axis is what
    # makes the raw traces honestly comparable.
    vis_raw_ax = fig.add_subplot(bc_gs[0, 2], sharey=mag_raw_ax)
    legend_gs = bc_gs[0, 1].subgridspec(2, 1, hspace=0.25)
    wheel_ax = fig.add_subplot(legend_gs[0, 0])
    waveform_ax = fig.add_subplot(legend_gs[1, 0])

    defgf_gs = outer_gs[2].subgridspec(1, 4, wspace=0.5)
    mag_spectra_ax = fig.add_subplot(defgf_gs[0, 0])
    mag_dist_ax = fig.add_subplot(defgf_gs[0, 1])
    vis_spectra_ax = fig.add_subplot(defgf_gs[0, 2])
    vis_dist_ax = fig.add_subplot(defgf_gs[0, 3])

    # ECDF is split by modality (rather than one combined panel), sharing a
    # y-axis so the two curves' deviation magnitudes are directly comparable.
    hi_gs = outer_gs[3].subgridspec(1, 2, wspace=0.35)
    ecdf_mag_ax = fig.add_subplot(hi_gs[0, 0])
    ecdf_vis_ax = fig.add_subplot(hi_gs[0, 1], sharey=ecdf_mag_ax)

    # ── Plot Row 1 ────────────────────────────────────────────────────────────
    # Cartoon placeholder
    cartoon_ax.add_patch(patches.Rectangle((0.05, 0.1), 0.9, 0.8, fill=False, edgecolor="black", linewidth=1))
    cartoon_ax.text(0.5, 0.5, "Neuropixel\nProbe", ha="center", va="center", fontsize=8)
    cartoon_ax.set_xlim(0, 1)
    cartoon_ax.set_ylim(0, 1)
    cartoon_ax.axis("off")

    # Mean-subtract only (no per-trace min-max rescaling) so panels B/C's
    # shared y-axis (see sharey above) reflects each trace's real amplitude
    # relative to the other, rather than both being independently stretched
    # to fill [0, 1].
    mean_subtract = lambda arr: arr - np.mean(arr)

    # Mag raw NPIX (null result) -- scale bar shows one stimulus period (1/freq)
    statistics.raw_NPIX(mag_raw_ax, None, mag_spks, None, MAG_WINDOW, MAG_FREQ,
                         label=1 / MAG_FREQ, trace=mag_trace, spike_sr=MAG_TRACE_SR,
                         raster_lw=RASTER_LW, phase_cmap=PHASE_CMAP, normalize=mean_subtract,
                         stem_scale=ARROW_STEM_SCALE)

    # Visual raw NPIX (positive result) -- same unit, same primitive as the mag panel
    statistics.raw_NPIX(vis_raw_ax, None, vis_spks, None, VIS_WINDOW, VIS_FREQ,
                         label=1 / VIS_FREQ, trace=vis_trace, spike_sr=VIS_TRACE_SR,
                         raster_lw=RASTER_LW, phase_cmap=PHASE_CMAP, normalize=mean_subtract,
                         stem_scale=ARROW_STEM_SCALE)

    # ── Plot Row 2: Magnetic stimulation (null) ──────────────────────────────
    statistics.plot_spectrum(mag_spectra_ax, fou_alt.flatten(), ff_alt, MAG_FREQ, fou0, legend=False,
                              real_color=FP.COLOR_MAG, imag_color=_lighten(FP.COLOR_MAG),
                              stem_color="black", sigma_color="gray")
    mag_spectra_ax.set_title("Magnetic")
    mag_spectra_ax.set_ylabel("Amplitude")
    mag_spectra_ax.set_xlabel("Freq (Hz)")
    statistics.boundary_ticks(mag_spectra_ax)
    statistics.nestle_labels(mag_spectra_ax, y=True, x=True, x_offset=-0.05)

    statistics.draw_hist(fourier_df.loc[fourier_df.rec == MAG_CONTINGENCY, "NFC"], mag_dist_ax, xlim=9,
                         inset=True, bar_color=FP.COLOR_MAG)
    mag_dist_ax.annotate("", (exemplar_NFC, 0.6), xytext=(exemplar_NFC, 0.8),
                         textcoords="data", arrowprops=dict(facecolor="black", arrowstyle="->"))
    statistics.boundary_ticks(mag_dist_ax, yprec=1)
    statistics.nestle_labels(mag_dist_ax, x_offset=-0.05, y_offset=-0.05)

    # ── Plot Row 3: Visual gratings (positive) ───────────────────────────────
    statistics.plot_spectrum(vis_spectra_ax, vis_fou_alt.flatten(), vis_ff_alt, VIS_FREQ, vis_fou0, legend=False,
                              real_color=FP.COLOR_VIS, imag_color=_lighten(FP.COLOR_VIS),
                              stem_color="black", sigma_color="gray")
    vis_spectra_ax.set_title("Visual")
    vis_spectra_ax.set_ylabel("Amplitude")
    vis_spectra_ax.set_xlabel("Freq (Hz)")
    statistics.boundary_ticks(vis_spectra_ax)
    statistics.nestle_labels(vis_spectra_ax, y=True, x=True, x_offset=-0.05)

    statistics.draw_hist(fourier_df.loc[fourier_df.rec == VIS_CONTINGENCY, "NFC"],
                         vis_dist_ax, xlim=12, inset=True, bar_color=FP.COLOR_VIS)
    # exemplar_NFC_vis (~7.79) sits out in this population's right tail --
    # consistent with this being a deliberately strong (tightly phase-
    # concentrated), not just barely-significant, exemplar (see module
    # docstring), on top of an already strong "positive control" population
    # (22% of units significant at this orientation).
    vis_dist_ax.annotate("", (exemplar_NFC_vis, 0.03), xytext=(exemplar_NFC_vis, 0.25),
                         textcoords="data", arrowprops=dict(facecolor="black", arrowstyle="->"))
    statistics.boundary_ticks(vis_dist_ax, yprec=1)
    statistics.nestle_labels(vis_dist_ax, x_offset=-0.05, y_offset=-0.05)

    # ── Kolmogorov-Smirnov diagnostic plot ────────────────────────────────────
    mag_NFC = fourier_df.loc[fourier_df.rec == MAG_CONTINGENCY, "NFC"].values
    vis_NFC = fourier_df.loc[fourier_df.rec == VIS_CONTINGENCY, "NFC"].values

    # Convert NFC to p-values
    mag_pvals = 1 - normalized_Fourier_CDF(mag_NFC)
    vis_pvals = 1 - normalized_Fourier_CDF(vis_NFC)

    # Plot mag K-S diagnostic: ECDF(x) - x with 95% CI
    mag_x, mag_lower, mag_upper = bootstrap_ecdf_band(mag_pvals, alpha=0.05)
    # Empirical ECDF at sorted points
    mag_ecdf = (np.arange(1, len(mag_pvals) + 1)) / len(mag_pvals)
    # K-S deviation: empirical ECDF minus theoretical (uniform) CDF
    mag_ks_dev = mag_ecdf - mag_x
    mag_ks_lower = mag_lower - mag_x
    mag_ks_upper = mag_upper - mag_x
    ecdf_mag_ax.plot(mag_x, mag_ks_dev, color=FP.COLOR_MAG, linewidth=FP.LW_TRACE, label=f"{MAG_FREQ:g} Hz (mag)")
    ecdf_mag_ax.fill_between(mag_x, mag_ks_lower, mag_ks_upper, color=FP.COLOR_MAG, alpha=FP.ALPHA_CONFIDENCE)
    ecdf_mag_ax.axhline(0, color=FP.COLOR_NULL, linestyle="--", linewidth=FP.LW_REFERENCE, alpha=0.6)
    ecdf_mag_ax.set_xlabel("p-value")
    ecdf_mag_ax.set_ylabel("ECDF deviation from null")
    ecdf_mag_ax.set_xlim((0, 1))
    ecdf_mag_ax.legend(loc="upper right", fontsize=7)
    statistics.boundary_ticks(ecdf_mag_ax)
    statistics.nestle_labels(ecdf_mag_ax, y=True, x_offset=-0.05)
    ecdf_mag_ax.spines["top"].set_visible(False)
    ecdf_mag_ax.spines["right"].set_visible(False)

    # Plot visual K-S diagnostic: ECDF(x) - x with 95% CI
    vis_x, vis_lower, vis_upper = bootstrap_ecdf_band(vis_pvals, alpha=0.05)
    # Empirical ECDF at sorted points
    vis_ecdf = (np.arange(1, len(vis_pvals) + 1)) / len(vis_pvals)
    # K-S deviation: empirical ECDF minus theoretical (uniform) CDF
    vis_ks_dev = vis_ecdf - vis_x
    vis_ks_lower = vis_lower - vis_x
    vis_ks_upper = vis_upper - vis_x
    ecdf_vis_ax.plot(vis_x, vis_ks_dev, color=FP.COLOR_VIS, linewidth=FP.LW_TRACE, label=f"{VIS_FREQ:g} Hz (visual)")
    ecdf_vis_ax.fill_between(vis_x, vis_ks_lower, vis_ks_upper, color=FP.COLOR_VIS, alpha=FP.ALPHA_CONFIDENCE)
    ecdf_vis_ax.axhline(0, color=FP.COLOR_NULL, linestyle="--", linewidth=FP.LW_REFERENCE, alpha=0.6)
    ecdf_vis_ax.set_xlabel("p-value")
    ecdf_vis_ax.set_xlim((0, 1))
    ecdf_vis_ax.legend(loc="upper right", fontsize=7)
    statistics.boundary_ticks(ecdf_vis_ax)
    statistics.nestle_labels(ecdf_vis_ax, y=True, x_offset=-0.05)
    ecdf_vis_ax.spines["top"].set_visible(False)
    ecdf_vis_ax.spines["right"].set_visible(False)

    # ── Phase colorwheel + average spike-waveform legend, stacked in the
    # narrow column between panels B and C (see legend_gs above) -- own
    # (blank) axes rather than insets over either raw-trace panel, so
    # neither needs an opaque backdrop to keep trace data from showing
    # through their titles/tick labels.
    statistics.plot_phase_colorwheel(wheel_ax, cmap=PHASE_CMAP, angle_unit="radians", fontsize=10)

    n_samples = waveforms.shape[1]
    half_width_samples = n_samples // 2
    t_ms = (np.arange(n_samples) - half_width_samples) / VIS_TRACE_SR * 1000
    for wf in waveforms:
        waveform_ax.plot(t_ms, wf, color="grey", linewidth=0.3, alpha=0.15)
    waveform_ax.plot(t_ms, waveforms.mean(axis=0), color="k", linewidth=1)
    waveform_ax.axis("off")

    fig.subplots_adjust(bottom=0, top=1, left=0, right=1)
    fig.canvas.draw()

    # ── Panel labels ──────────────────────────────────────────────────────────
    _label_kw = dict(xycoords="axes fraction", fontfamily="arial", fontsize=11, weight="bold")
    cartoon_ax.annotate("A", xy=(-0.03, 1.1), **_label_kw)
    mag_raw_ax.annotate("B", xy=(-0.05, 1.1), **_label_kw)
    vis_raw_ax.annotate("C", xy=(-0.05, 1.1), **_label_kw)
    mag_spectra_ax.annotate("D", xy=(-0.15, 1.1), **_label_kw)
    vis_spectra_ax.annotate("G", xy=(-0.15, 1.1), **_label_kw)
    mag_dist_ax.annotate("E", xy=(-0.15, 1.1), **_label_kw)
    vis_dist_ax.annotate("F", xy=(-0.15, 1.1), **_label_kw)
    ecdf_mag_ax.annotate("H", xy=(-0.15, 1.1), **_label_kw)
    ecdf_vis_ax.annotate("I", xy=(-0.15, 1.1), **_label_kw)
    out_path = out_dir / "Fig1.pdf"
    fig.savefig(out_path, bbox_inches="tight", dpi=FP.DPI)
    print(f"Saved {out_path}")
    if not in_notebook:
        plt.close(fig)


def main():
    parser = argparse.ArgumentParser(description="Generate Fig 1 (composite NPIX null + positive + ECDFs)")
    parser.add_argument("--out-dir", default=FP.OUT_DIR, help="Output directory for PDFs")
    parser.add_argument("--data-dir", default=FP.DATA_DIR, help="Directory containing pipeline output pickles")
    args = parser.parse_args([] if in_notebook else None)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Loading NPIX data...")
    modulation_df, fourier_df, group_df, unit_df = load_data(args.data_dir)
    plot_fig1_composite(modulation_df, fourier_df, group_df, unit_df, out_dir)


if __name__ == "__main__":
    if in_notebook:
        # Programmatic equivalent of the `%config` IPython magic -- same
        # effect (retina figure format for inline display), but doesn't
        # require IPython's magic-command preprocessing, so this file stays
        # runnable via plain `python fig1.py` too, not just `%run` inside a
        # live IPython/Jupyter session.
        get_ipython().run_line_magic("config", "InlineBackend.figure_format = 'retina'")
    main()
